/*********************DBA Database*********************/
USE [master];

-- Create DBA_Monitoring Database
CREATE DATABASE [DBA_Monitoring];
GO

IF (FULLTEXTSERVICEPROPERTY('IsFullTextInstalled') = 1)
BEGIN
	EXEC [DBA_Monitoring].[dbo].[sp_fulltext_database] @action = 'enable';
END;

ALTER DATABASE [DBA_Monitoring] SET ANSI_NULL_DEFAULT OFF;
ALTER DATABASE [DBA_Monitoring] SET ANSI_NULLS OFF;
ALTER DATABASE [DBA_Monitoring] SET ANSI_PADDING OFF;
ALTER DATABASE [DBA_Monitoring] SET ANSI_WARNINGS OFF;
ALTER DATABASE [DBA_Monitoring] SET ARITHABORT OFF;
ALTER DATABASE [DBA_Monitoring] SET AUTO_CLOSE OFF;
ALTER DATABASE [DBA_Monitoring] SET AUTO_CREATE_STATISTICS ON;
ALTER DATABASE [DBA_Monitoring] SET AUTO_SHRINK OFF;
ALTER DATABASE [DBA_Monitoring] SET AUTO_UPDATE_STATISTICS ON;
ALTER DATABASE [DBA_Monitoring] SET CURSOR_CLOSE_ON_COMMIT OFF;
ALTER DATABASE [DBA_Monitoring] SET CURSOR_DEFAULT GLOBAL;
ALTER DATABASE [DBA_Monitoring] SET CONCAT_NULL_YIELDS_NULL OFF;
ALTER DATABASE [DBA_Monitoring] SET NUMERIC_ROUNDABORT OFF;
ALTER DATABASE [DBA_Monitoring] SET QUOTED_IDENTIFIER OFF;
ALTER DATABASE [DBA_Monitoring] SET RECURSIVE_TRIGGERS OFF;
ALTER DATABASE [DBA_Monitoring] SET DISABLE_BROKER;
ALTER DATABASE [DBA_Monitoring] SET AUTO_UPDATE_STATISTICS_ASYNC OFF;
ALTER DATABASE [DBA_Monitoring] SET DATE_CORRELATION_OPTIMIZATION OFF;
ALTER DATABASE [DBA_Monitoring] SET TRUSTWORTHY OFF;
ALTER DATABASE [DBA_Monitoring] SET ALLOW_SNAPSHOT_ISOLATION OFF;
ALTER DATABASE [DBA_Monitoring] SET PARAMETERIZATION SIMPLE;
ALTER DATABASE [DBA_Monitoring] SET READ_COMMITTED_SNAPSHOT OFF;
ALTER DATABASE [DBA_Monitoring] SET HONOR_BROKER_PRIORITY OFF;
ALTER DATABASE [DBA_Monitoring] SET RECOVERY FULL;
ALTER DATABASE [DBA_Monitoring] SET MULTI_USER;
ALTER DATABASE [DBA_Monitoring] SET PAGE_VERIFY CHECKSUM;
ALTER DATABASE [DBA_Monitoring] SET DB_CHAINING OFF;
ALTER DATABASE [DBA_Monitoring]
SET FILESTREAM
	(
		NON_TRANSACTED_ACCESS = OFF
	);
   
ALTER DATABASE [DBA_Monitoring] SET TARGET_RECOVERY_TIME = 0 SECONDS;
ALTER DATABASE [DBA_Monitoring] SET READ_WRITE;
ALTER DATABASE [DBA_Monitoring] SET PARAMETERIZATION FORCED WITH NO_WAIT
GO

CREATE TABLE [DBA_Monitoring].[dbo].[tempdb_Data]
(
	[program_name] NVARCHAR(128) NULL
   ,[No column name1] VARCHAR(1) NULL
   ,[host_name] NVARCHAR(128) NULL
   ,[No column name2] VARCHAR(1) NULL
   ,[Session_ID] SMALLINT NULL
   ,[No column name3] VARCHAR(1) NULL
   ,[Login_Name] NVARCHAR(128) NULL
   ,[No column name4] VARCHAR(1) NULL
   ,[Command] NVARCHAR(32) NULL
   ,[No column name5] VARCHAR(1) NULL
   ,[Task_Alloc] BIGINT NULL
   ,[No column name6] VARCHAR(1) NULL
   ,[Task_Dealloc] BIGINT NULL
   ,[No column name7] VARCHAR(1) NULL
   ,[sql_handle] NVARCHAR(MAX) NULL
   ,[sql_plan] XML NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];

SET ANSI_PADDING OFF;
GO
